<a href="https://colab.research.google.com/github/jjAguil/Tareas-Simulacion/blob/main/Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy. Clase 2
La sesión pasada nos enfocamos en una introducción a la librería Numpy, sus
bondades y ventajas, además de dar algunos ejemplos y resolver algunos
ejercicios.

Daremos un breve repaso sobre lo ya aprendido

## Repaso

### Operaciones elemento por elemento (elementwise)



In [ ]:
import numpy as np

# crear arreglos
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
result = a + b
print(result)  # Output: [6 8 10 12]

# Operaciones matemáticas entre arreglos
c = np.array([10, 20, 30, 40])
result = (a + b) * c
print(result)

[ 6  8 10 12]
[ 60 160 300 480]


### Broadcasting

In [ ]:
# crear arreglos de diferentes shapes
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])

# realizar operacion sobre ambos. Numpy se encarga de todo
result = a + b
print(result)

[[11 22]
 [13 24]]


### Algunas funciones



In [ ]:
# crear datos
data = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])

# suma todos los elementos
sum_todos = np.sum(data)
print(sum_todos)

# Promedio sobre el eje 0, promedio de columnas
media_eje_0 = np.mean(data, axis=0)
print(media_eje_0)

# Promedio sobre el eje 1, promedio de filas
media_eje_1 = np.max(data, axis=1)
print(media_eje_1)

**Fin del repaso**
## Operaciones Booleanas
En Numpy, las operaciones Booleanas (lógicas) nos permiten manipular y filtrar
nuestros arreglos basándonos en proposiciones lógicas, es decir condiciones que
evalúan a `True` o `False`.

Numpy permite que las operaciones booleanas se realicen elemento por elemento,
es decir, podemos comparar entre arreglos, o elementos contra arreglos. Esto
dará como resultado un nuevo arreglo, que nos indica el resultado de la
comparación. Entre los operadores más comunes encontramos:
- Igualdad: `==`
- Desigualdad: `!=`
- Mayor que: `>`
- Mayor o igual que: `>=`
- Menor que: `<`
- Menor o igual que: `<=`
   

In [ ]:
"""
ejemplo 1.
Crear dos arreglos y comparar si los elementos en arr1 son mayores a su
correspondiente elemento en arr 2
"""
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 3, 2, 4, 1])

result = arr1 > arr2
print("Ejemplo 1")
print(result)


"""
ejemplo 2.
Checar si los elementos de un arreglo son pares
Si el módulo (restante) de un número entre 2 es cero, el número es par
"""
arr3 = np.array([[1, 2, 3, 4, 5, 6], [2, 3, 4, 5, 6, 7]])
result = arr3 % 2 == 1
print("\nEjemplo 2")
print(arr3)
print(result)
print(arr3[~result])

Ejemplo 1
[False False  True False  True]

Ejemplo 2
[[1 2 3 4 5 6]
 [2 3 4 5 6 7]]
[[ True False  True False  True False]
 [False  True False  True False  True]]
[2 4 6 2 4 6]


## Máscaras Booleanas
Una máscar Booleana es un arreglo que contiene valores `True` o `False`, tal
como los que obtuvimos en la sección anterior. Estos arreglos pueden servir como
filtros para seleccionar elementos específicos, ya sea del mismo arreglo o de un
arreglo diferente. Para lograrlo, usamos la máscara como método de indexado del
arreglo.


In [ ]:
"""
ejemplo: indexado avanzado mediante listas
"""
arr = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [6, 5, 4, 3, 2]])
# podemos obtener las columnas 0 y 4 pasando una lista en el índice correspondiente
print("Indexado mediante listas")
print(f"arreglo original:\n{arr}")
print(f"\nrecuperar columnas 0 y 4:\n{arr[:, [0, 4]]}")
print(f"\nrecuperar columnas 1, 2 y 4:\n{arr[:, [1, 2, 4]]}")


Indexado mediante listas
arreglo original:
[[1 2 3 4 5]
 [2 3 4 5 6]
 [6 5 4 3 2]]

recuperar columnas 0 y 4:
[[1 5]
 [2 6]
 [6 2]]

recuperar columnas 1, 2 y 4:
[[2 3 5]
 [3 4 6]
 [5 4 2]]


In [ ]:
"""
ejemplo: indexado avanzado mediante arrays
"""
arr = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [6, 5, 4, 3, 2]])
# podemos obtener las columnas 0 y 4 pasando una lista en el índice correspondiente
print("\nIndexado mediante arrays")
print(f"arreglo original:\n{arr}")
arr_cols = np.array([0, 4])
print(f"\nrecuperar columnas 0 y 4:\n{arr[:, arr_cols]}")
arr_cols = np.array([1, 2, 4])
print(f"\nrecuperar columnas 1, 2 y 4:\n{arr[:, arr_cols]}")


Indexado mediante arrays
arreglo original:
[[1 2 3 4 5]
 [2 3 4 5 6]
 [6 5 4 3 2]]

recuperar columnas 0 y 4:
[[1 5]
 [2 6]
 [6 2]]

recuperar columnas 1, 2 y 4:
[[2 3 5]
 [3 4 6]
 [5 4 2]]


In [ ]:
"""
ejemplo: uso de máscaras booleanas
Recuperamos únicamente los elementos donde la máscara tiene valor `True`
"""
# crear arreglo y encontrar todo aquellos elementos que sean mayores que 2
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 2

# Usando la máscara, obtener un nuevo arreglo con los valores correspondientes
array_filtrado = arr[mask]
print("\nUso de mascaras booleanas")
print(f"arreglo original:\n{arr}")
print(f"mascara:\n{mask}")
print(f"arreglo filtrado:\n{array_filtrado}")

# asignacion de valores de acuerdo a la mascara
print("\nUso de mascaras booleanas")
print(f"arreglo original:\n{arr}")
arr[mask] = 0  # donde la mascara es True, asigna el valor cero
print(f"arreglo despues de asignacion:\n{arr}")


Uso de mascaras booleanas
arreglo original:
[1 2 3 4 5]
mascara:
[False False  True  True  True]
arreglo filtrado:
[3 4 5]

Uso de mascaras booleanas
arreglo original:
[1 2 3 4 5]
arreglo despues de asignacion:
[1 2 0 0 0]


También se pueden combinar varias condiciones booleanas mediante el uso de
operadores lógicos, por ejemplo:
- `&` (and): evalúa a `True` si ambos lados de la condición son `True`, en
cualquier otro caso evalúa a `False`
- `|` (or): evalúa a `False` si ambos lados de la condición son `False`, en
cualquier otro caso evalúa a `True`
- `~` (not): cambia el valor de la condición, si era `False` pasa a ser `True` y
viceversa, de `True` a `False`

In [ ]:
"""
ejemplo: uso de operadores
"""
arr = np.arange(11)
mask_1 = arr > 2
mask_2 = arr < 8
mask = mask_1 & mask_2
# mask = (arr > 2) & (arr < 8)

print("Ejemplo de operador &")
print(f"arreglo original:\n{arr}")
print(f"mascara 1:\n{mask_1}")
print(f"mascara 2:\n{mask_2}")
print(f"mascara completa:\n{mask}")


mask = mask_1 | mask_2
print("\n\nEjemplo de operador |")
print(f"arreglo original:\n{arr}")
print(f"mascara 1:\n{mask_1}")
print(f"mascara 2:\n{mask_2}")
print(f"mascara completa:\n{mask}")



mask = arr % 2 == 0
mask_neg = ~mask
print("\n\nEjemplo de operador ~")
print(f"arreglo original:\n{arr}")
print(f"mascara original:\n{mask}")
print(f"mascara negada:\n{mask_neg}")

Ejemplo de operador &
arreglo original:
[ 0  1  2  3  4  5  6  7  8  9 10]
mascara 1:
[False False False  True  True  True  True  True  True  True  True]
mascara 2:
[ True  True  True  True  True  True  True  True False False False]
mascara completa:
[False False False  True  True  True  True  True False False False]


Ejemplo de operador |
arreglo original:
[ 0  1  2  3  4  5  6  7  8  9 10]
mascara 1:
[False False False  True  True  True  True  True  True  True  True]
mascara 2:
[ True  True  True  True  True  True  True  True False False False]
mascara completa:
[ True  True  True  True  True  True  True  True  True  True  True]


Ejemplo de operador ~
arreglo original:
[ 0  1  2  3  4  5  6  7  8  9 10]
mascara original:
[ True False  True False  True False  True False  True False  True]
mascara negada:
[False  True False  True False  True False  True False  True False]


## Masked arrays
En Numpy, los *masked arrays* son una estructura de datos que permite trabajar
con arreglos que contengan valores perdidos o datos inválidos, esto mediante la
incorporación de una máscara booleana, que indica cuáles elementos son
válidos y cuáles no. Esta herramienta es muy importante en Data Science, ya que
en muchos casos contamos con valores perdidos. Estos arreglos nos permiten
continuar trabajando con nuestro dataset ignorando por completo lo que no nos
sirve.

La idea detrás de los *masked arrays* es tener dos arreglos: uno con los datos,
y otro con la máscara. La máscara debe tener la misma *shape* que el arreglo de
datos, pero sus valores deben de ser booleanos (`True` o `False`). El valor
`True` nos indica que es un valor inválido.

Para crear un arreglo enmascarado, se usa la función `np.ma.array()`, que permite
pasar un arreglo de datos y uno de máscara simultáneamente.



In [ ]:
"""
crear arreglo de datos y mascara
el cuarto valor (-999) será inválido, por ello, la máscara solo evalúa a True en
ese elemento
"""

datos = np.array([1, 2, 3, -999, 5])
mask = np.array([False, False, False, True, False])

# obtener masked array
masked_data = np.ma.masked_array(datos, mask=mask)
print(masked_data)


En el ejemplo anterior, el elemento con valor `-999` se marcó como inválido
mediante el arreglo de máscara (haciendo `True` únicamente ese elemento, y
`False` todos los demás). Cuando imprimimos el arreglo, Numpy omite el valor
`-999` y muestre simplemente los símbolos `--` para denotar la presencia de un
elemento inválido.


Toda vez que se cuenta con un masked array, se pueden llevar a cabo diversas
operaciones sobre el. Básicamente, todos los elementos marcados como invalidos
son omitidos en las operaciones matemáticas, por ejemplo: suma, resta,
multiplicación y división.



In [ ]:
# obtener masked array
datos = np.array([1, 2, 3, -999, 5])
mask = np.array([False, False, False, True, False])
masked_data = np.ma.masked_array(datos, mask=mask)

# Operations with masked array
print(f"arreglo original:\n{datos}")
print(f"suma de arreglo original:\n{data.sum()}")
print(f"suma de arreglo con mascara:\n{masked_data.sum()}")

print()
print(f"promedio de arreglo original:\n{data.mean()}")
print(f"promedio de arreglo con mascara:\n{masked_data.mean()}")

Aparte de operaciones matemáticas, estos arreglos soportan operaciones tales
como: slicing, indexado y broadcasting.

Aparte de crear masked array de modo manual, existen funciones que pueden
crearlos automáticamente, a partir de una condición lógica, por ejemplo, las
funciones: `numpy.ma.masked_invalid()` y `numpy.ma.masked_where()`



In [ ]:
"""
ejemplo: crear arreglo con función `masked_invalid` que en automático define
valors como: nan (not a number), inf, -inf como invalidos
"""
datos = np.array([1, 2, 3, np.inf, 5])
masked_data = np.ma.masked_invalid(datos)
print(f"Arreglo creado con masked_invalid:\n{masked_data}")

"""
ejemplo: crear un masked array considerando como invalidos todos aquellos
valores mayores a 3
"""
datos = np.array([1, 2, 3, np.inf, 5])
masked_data = np.ma.masked_where(data > 3, datos)
print(f"Arreglo creado con masked_:\n{masked_data}")

## Ejercicios
### Suma de un vector a una matriz
Sumar un vector (array unidimensional) a cada fila de una matriz (array bidimensional).

- Crea una matriz AA de tamaño 3×3 con números enteros del 1 al 9.
- Crea un vector vv de tamaño 3 con números enteros del 1 al 3.
- Usa broadcasting para sumar vv a cada fila de AA.

### Comparaciones elemento a elemento
Comparar dos arrays elemento a elemento y generar un array booleano que indique cuáles elementos cumplen la condición.
- Crea dos arrays AA y BB de tamaño 5 con números enteros.
- Compara elemento a elemento si los valores en AA son mayores que los valores en BB.
- Genera un array booleano que contenga el resultado de la comparación.

### Filtrado de elementos usando comparaciones
Filtrar los elementos de un array que cumplen una cierta condición.

- Crea un array AA de tamaño 10 con números enteros del 0 al 9.
- Usa una condición para filtrar los elementos de AA que sean mayores que 5.
- Genera un nuevo array que contenga solo los elementos que cumplan la condición.

### Comparaciones con múltiples condiciones

Aplicar múltiples condiciones para filtrar los elementos de un array.

- Crea un array AA de tamaño 10 con números enteros del 0 al 9.
- Usa dos condiciones para filtrar los elementos de AA: valores mayores que 3 y menores que 8.
- Genera un nuevo array que contenga solo los elementos que cumplan ambas condiciones.

### Filtrado y Modificación de Arrays

Dado un array de números enteros, modifica los elementos que no cumplan con una serie de condiciones. En este ejercicio, las condiciones serán que los elementos deben ser mayores que 3 y menores que 8. Los elementos que no cumplan con estas condiciones deben ser reemplazados por -1.
- Crea un array AA de números enteros del 0 al 9.
- Identifica los elementos que no son mayores que 3 o que no son menores que 8.
- Reemplaza estos elementos por -1.
- Imprime el array original y el array modificado.

### Calcular Senos y Cosenos

Calcular los senos y cosenos de un array de ángulos dados en grados y convertir los resultados a grados.

- Crea un array de ángulos en grados (por ejemplo, 0, 30, 45, 60, 90).
- Convierte estos ángulos a radianes.
- Calcula los senos y cosenos de estos ángulos en radianes.
- Convierte los resultados de senos y cosenos a grados.